"""add trip scheduling fields

Revision ID: 3399a2605be0
Revises: 09ea02581086
Create Date: 2026-06-12 15:38:23.021730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3399a2605be0"
down_revision: Union[str, Sequence[str], None] = "09ea02581086"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trips", sa.Column("scheduled_start_at", sa.DateTime(), nullable=True)
    )
    op.add_column("trips", sa.Column("started_at", sa.DateTime(), nullable=True))
    op.add_column("trips", sa.Column("expected_end_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "expected_end_at")
    op.drop_column("trips", "started_at")
    op.drop_column("trips", "scheduled_start_at")
    # ### end Alembic commands ###
