"""add charging sessions table

Revision ID: 63198edd417e
Revises: b086eb75d2c2
Create Date: 2026-06-09 18:16:02.435604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "63198edd417e"
down_revision: Union[str, Sequence[str], None] = "b086eb75d2c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charging_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("start_soc", sa.Float(), nullable=False),
        sa.Column("target_soc", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "start_soc >= 0 AND start_soc <= 100", name="check_start_soc"
        ),
        sa.CheckConstraint(
            "target_soc > start_soc", name="check_target_greater_than_start"
        ),
        sa.CheckConstraint(
            "target_soc >= 0 AND target_soc <= 100", name="check_target_soc"
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["charging_stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_charging_sessions_id"), "charging_sessions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_charging_sessions_id"), table_name="charging_sessions")
    op.drop_table("charging_sessions")
    # ### end Alembic commands ###
