"""add station charging metrics

Revision ID: 6717a6497abc
Revises: 3399a2605be0
Create Date: 2026-06-12 16:09:49.990693

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6717a6497abc"
down_revision: Union[str, Sequence[str], None] = "3399a2605be0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        "charging_stations",
        sa.Column(
            "max_power_kw",
            sa.Integer(),
            nullable=False,
            server_default="60",
        ),
    )

    op.add_column(
        "charging_stations",
        sa.Column(
            "avg_queue_minutes",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("charging_stations", "avg_queue_minutes")
    op.drop_column("charging_stations", "max_power_kw")
    # ### end Alembic commands ###
