"""vehicle status enum

Revision ID: 8ce966113719
Revises:
Create Date: 2026-06-08 17:36:43.909076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8ce966113719"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vehicles",
        "status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "AVAILABLE",
            "CHARGING",
            "ON_TRIP",
            "MAINTENANCE",
            "OFFLINE",
            name="vehiclestatus",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vehicles",
        "status",
        existing_type=sa.Enum(
            "AVAILABLE",
            "CHARGING",
            "ON_TRIP",
            "MAINTENANCE",
            "OFFLINE",
            name="vehiclestatus",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
