"""add charging stations table

Revision ID: b086eb75d2c2
Revises: cab7266a4dd0
Create Date: 2026-06-09 18:01:01.726205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b086eb75d2c2"
down_revision: Union[str, Sequence[str], None] = "cab7266a4dd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charging_stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location_name", sa.String(), nullable=False),
        sa.Column("total_chargers", sa.Integer(), nullable=False),
        sa.Column("available_chargers", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "available_chargers <= total_chargers", name="check_available_chargers"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_charging_stations_id"), "charging_stations", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_charging_stations_id"), table_name="charging_stations")
    op.drop_table("charging_stations")
    # ### end Alembic commands ###
